spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  jwt:
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
